### ISSUE TITLE
NameList ToDos

### ISSUE THREAD

**Issue by aexlz** [aexlz/verteilte_systeme_rmi#1]
1. "\@Override" für die Methode, welche im Interface deklariert wurde (in NameListImpl)
2. Methode im Interface muss von Remote erben --> void main nur zum lokalen Testen der Klasse notwendig. Gilt es zu ersetzen im RMI-Betrieb

**Comment by jschacht7** [comment]
1. Überall gemacht.
2. Server Interface das Remote erweitert mit benötigter Methode geschrieben -> Methode in NameListImpl wird von Server Implementierung aufgerufen.
