### ISSUE TITLE
Fehlerfälle

### ISSUE THREAD

**Issue by jschacht7** [aexlz/verteilte_systeme_rmi#4]
1. Client sucht Nachnamen, der nicht in Liste des Servers steht.
2. Client wird ohne Nachname aufgerufen.
3. Client wird mit zu vielen Nachnamen aufgerufen.

---
To be expanded

**Comment by aexlz** [comment]
Aktuell wird der Fehler der "zu vielen" oder "zu wenigen" Nachnamen nur im NameListParserXML über ne Exception abgefangen. Mein Ziel war es jetzt, dass RmiServerImpl (mit String[] surnames) die NameListImpl aufruft, die (mit String[] surnames) wiederum den NameListParserXML aufruft. Dieser gibt eigentlich die HashMap zurück. Quick-and-dirty-Lösung wäre hier einfach der Kette entlang 'null' zu returnen. Dem Client den Fehler zu melden ist dann die Aufgabe von RmiServerImpl...Ob dieser in dem zu erwartenden Datenkonstrukt (in dem Fall HashMap) stehen muss, zweifel ich an. Könnte mir vorstellen, dass Remote eine Schnittstelle besitzt, die es erlaubt, einen Log an den Client zu schicken nach dem Motto "Fehlerhafte Eingabe"

**Comment by aexlz** [comment]
Fehler 1 "abgefangen"

**Comment by aexlz** [comment]
Zu viele/wenige Argumente auf Client-Seite abgefangen!
